apiVersion: apps/v1
kind: Deployment
metadata:
  name: boutique
  namespace: default
  labels:
    app: boutique
spec:
  replicas: 3   # 3 Pods en permanence
  selector:
    matchLabels:
      app: boutique
  template:
    metadata:
      labels:
        app: boutique
    spec:
      containers:
        - name: boutique
          # ⚠ Remplacez VOTRE_USERNAME par votre nom d'utilisateur GitHub
          image: ghcr.io/VOTRE_USERNAME/tp_devops:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: boutique-config   # injecte toutes les vars du ConfigMap
            - secretRef:
                name: boutique-secret   # injecte toutes les vars du Secret
          resources:
            requests:
              cpu: "100m"     # 0.1 CPU garanti
              memory: "128Mi" # 128 Mo garanti
            limits:
              cpu: "500m"     # max 0.5 CPU
              memory: "256Mi" # max 256 Mo
